export default [
    {
        title:"首页",
        key:"/admin/home",
    },
    {
        title:"UI",
        key:"/admin/ui",
        childern:[
            {
                title:"按钮",
                key:"/admin/ui/buttons"
            },
            {
                title:"弹窗",
                key:"/admin/ui/modals"
            },
            {
                title:"Loading",
                key:"/admin/ui/loading"
            }
        ]
    },
    {
        title:"图表",
        key:"/admin/charts",
        childern:[
            {
                title:"柱形图",
                key:"/admin/charts/bar"
            },
            {
                title:"饼图",
                key:"/admin/charts/pie"
            },
            {
                title:"折线图",
                key:"/admin/charts/line"
            }
        ]
    },
    {
        title:"权限设置",
        key:"/admin/quanxian",
    }
]